import CONFIG from '../config';

export const BACKEND_URL = CONFIG.BASE_URL;
export const BASE_URL = BACKEND_URL + '/api/v1';
export const COMPANY = 'company';
export const AUTH = 'auth';
export const LOGIN = 'login';
export const SHIPMENT = 'shipment';
export const CURRENT = 'current';
export const FINISHED = 'finished';
export const WAY = 'way';
export const DRIVERS = 'drivers';
export const USER = 'user';
export const CLIENT = 'client';
export const NOTE = 'note';
export const ITEMS = 'items';
export const ADD_CLIENT_AND_SHIPMENT_ITEM = 'add-client-and-shipment-item';
export const MOVE_SHIPMENT_WITH_NOTIFICATION = 'move-shipment-with-notification';
export const MOVE_SHIPMENT_WITHOUT_NOTIFICATION = 'move-shipment-without-notification';
export const PAUSE_SHIPMENT = 'pause-shipment';
export const RESUME_SHIPMENT = 'resume-shipment';
