import type {Metadata} from 'next';
import './globals.css';
import localFont from 'next/font/local';
import ProviderQueryClient from '@/lib/react-query';
import {Toaster} from '@/components/ui/sonner';
import AuthContextProvider from '@/context/auth-context';
import {getUser} from '@/lib/utils';
import {cookies} from 'next/headers';

const myFont = localFont({
  src: './../public/Fonts/IBMPlexSansArabic-Medium.ttf'
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = await cookies();
  const token = cookie.get('token')?.value;
  const user = token ? getUser(token) : null;
  const value = {user, isAuthenticated: !!user?.id};
  return (
    <html lang='en'>
      <body className={`${myFont.className} antialiased`}>
        <ProviderQueryClient>
          <AuthContextProvider value={value}>
            {children}
            <Toaster richColors position='top-right' />
          </AuthContextProvider>
        </ProviderQueryClient>
      </body>
    </html>
  );
}
