import type {Metadata} from 'next';
import './globals.css';
import localFont from 'next/font/local';
import ProviderQueryClient from './_provider/reactQuery';
import {Toaster} from './_components/ui/sonner';

const myFont = localFont({
  src: './../public/Fonts/IBMPlexSansArabic-Medium.ttf'
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${myFont.className} antialiased`}>
        <ProviderQueryClient>
          {children}
          <Toaster richColors />
        </ProviderQueryClient>
      </body>
    </html>
  );
}
